host01:
  log_dir: /tmp/logs
  dce_md_publisher:
    binary: md_server
    tag: prod
    templates:
      - name: dce_md_publisher.json
        cfg_envs:
          log_cpu: 0  # numa 0
          main_loop_cpu: 3  # numa 0
          admin_loop_cpu: 1  # numa 0
          listen_nic: sf0  # 192.168.1.101
          listen_port: 12800
          broadcast_queue_shm_path: /dev/shm/dce_md_publisher_broadcast_queue
  dce_md_recorder:
    depends_on: 
      - dce_md_publisher
    binary: md_recorder
    tag: prod
    templates:
      - name: dce_md_recorder.json
        cfg_envs:
          log_cpu: 0  # numa 0
          main_loop_cpu: 2  # numa 0
          admin_loop_cpu: 1  # numa 0
host02:
  log_dir: /tmp/logs
  dce_md_recorder_backup:
    depends_on: 
      - dce_md_publisher
    binary: md_recorder
    tag: prod
    templates:
      - name: dce_md_recorder_backup.json
        cfg_envs:
          log_cpu: 0  # numa 1
          main_loop_cpu: 2  # numa 1
          admin_loop_cpu: 1  # numa 0
