host01:
  dce_md_publisher:
    binary: md_server
    version: v1.2.4-rc1
    templates:
      - name: dce_md_publisher.json
        cfg_envs:
          listen_nic: sf0  # 192.168.1.101
          listen_port: 8080
          log_cpu: 0  # numa 0
          main_loop_cpu: 15  # numa 1
          admin_loop_cpu: 1  # numa 0
