defaults:
  timezone: Asia/Shanghai

schedules:
  dce_md_publisher:
    rules:
      - sessions:
          - ["09:00", "15:10"] # Day Session
          - ["21:00", "04:10"] # Night Session (to the next day)
        days: "mon-fri"